plugins:
  discourse_chronos_enabled:
    default: true
    client: true
  discourse_chronos_default_formats:
    default: "LLL|MMM Do YY H:mm|MMMM Do YYYY, h:mm:ss a"
    client: true
    type: list
  discourse_chronos_default_timezones:
    default: "Europe/Paris|America/Los_Angeles"
    client: true
    type: list
